parameters:
#    sopinet_simple_point.example.class: Sopinet\SimplePointBundle\Example

services:
#    sopinet_simple_point.example:
#        class: %sopinet_simple_point.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
